[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_bootcamp_project = "4QKU2dkXGRTGFbR5e5tDQFitFrjVXLnWuKN71iHrZRBo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/liaoyichun/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
